language: cpp
dist: xenial
compiler: g++
sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.6-xenial
  - sudo apt-get -qy update
  - sudo apt-get install -qq g++-8 gcc-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
  - sudo apt-get install -qq qt512-meta-minimal
  - sudo apt-get install -qq libx11-xcb-dev libglu1-mesa-dev
  - export QT_DIR=/opt/qt512
  - export QMAKE=$QT_DIR/bin/qmake
  - export PATH=$QT_DIR/bin/:$PATH
  #- sudo apt-get install qtbase5-dev libqwt-qt5-dev libqwt-qt5-6
  #- sudo apt-get install qt5-qmake
  #- sudo apt-get install qmlscene
  #- sudo apt-get install qtbase5-dev-tools
  #- sudo apt-get install libqt5quick5 libqt5qml5
  #- sudo apt-get install libqt5svg5-dev
  #- sudo apt-get install libqt5svg5 
  - sudo apt-get install libnetcdf-dev libnetcdf11
  
before_script:
  - gcc --version
  - g++ --version
  - $QMAKE -v

script: 
    - bash deploy/PRAGA/build.sh
    
after_success:
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - bash upload.sh *.AppImage*

